# Generated by Django 5.2.4 on 2026-06-10 12:19

import apps.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        default=apps.auth.models.generate_user_id,
                        help_text="8-character numeric identifier for the user",
                        max_length=8,
                        unique=True,
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(
                        help_text="Argon2 hash of client-derived authentication secret",
                        max_length=128,
                    ),
                ),
                (
                    "auth_salt",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Salt for client-side authentication secret derivation",
                        max_length=64,
                    ),
                ),
                (
                    "vault_salt",
                    models.CharField(
                        help_text="Salt for client-side vault key derivation (PBKDF2-SHA256)",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "proxima_user",
            },
        ),
    ]
