# Generated by Django 5.2.15 on 2026-07-13 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxima_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(help_text='Base64 SPKI ECDH P-256 public key (server-distributed)', max_length=256)),
                ('encrypted_private_key', models.CharField(help_text='Base64 AES-GCM ciphertext of the PKCS8 private key (vault key)', max_length=512)),
                ('private_key_iv', models.CharField(help_text='Base64 IV for the encrypted private key blob', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keypair', to='proxima_auth.user')),
            ],
            options={
                'verbose_name': 'User keypair',
                'verbose_name_plural': 'User keypairs',
                'db_table': 'proxima_user_keypair',
            },
        ),
    ]
