# Generated by Django 5.2.15 on 2026-07-06 13:35

import apps.note.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("proxima_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this shared note",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Note body: Base64 ciphertext when encrypted, raw markdown when plain text",
                        validators=[apps.note.validators.validate_note_content],
                    ),
                ),
                (
                    "iv",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Initialization vector for AES-GCM encryption (Base64-encoded); empty for plain-text notes",
                        validators=[apps.note.validators.validate_optional_iv],
                    ),
                ),
                (
                    "is_encrypted",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the content was encrypted client-side",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this note was created",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Timestamp when this note expires and will be deleted"
                    ),
                ),
                (
                    "access_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this note has been accessed",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Authenticated user that created this note; empty for anonymous notes",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_notes",
                        to="proxima_auth.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shared Note",
                "verbose_name_plural": "Shared Notes",
                "db_table": "note_sharednote",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["expires_at"], name="note_expires_idx"),
                    models.Index(fields=["-created_at"], name="note_created_idx"),
                ],
            },
        ),
    ]
