# Generated by Django 5.2.15 on 2026-07-11 21:18

import apps.note.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
        ('proxima_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_data', models.TextField(help_text='Base64 AES-256-GCM ciphertext of the vault index JSON', validators=[apps.note.validators.validate_vault_index_data])),
                ('iv', models.TextField(help_text='Initialization vector for AES-GCM encryption (Base64-encoded)', validators=[apps.note.validators.validate_required_iv])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this index was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last index save')),
                ('user', models.OneToOneField(help_text='Account that owns this vault index', on_delete=django.db.models.deletion.CASCADE, related_name='note_vault_index', to='proxima_auth.user')),
            ],
            options={
                'verbose_name': 'Vault Index',
                'verbose_name_plural': 'Vault Indexes',
                'db_table': 'note_vaultindex',
            },
        ),
        migrations.CreateModel(
            name='VaultNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this vault note', primary_key=True, serialize=False)),
                ('content', models.TextField(help_text="Base64 AES-256-GCM ciphertext of the note's markdown", validators=[apps.note.validators.validate_vault_note_content])),
                ('iv', models.TextField(help_text='Initialization vector for AES-GCM encryption (Base64-encoded)', validators=[apps.note.validators.validate_required_iv])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this note was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last content update')),
                ('user', models.ForeignKey(help_text='Account that owns this vault note', on_delete=django.db.models.deletion.CASCADE, related_name='vault_notes', to='proxima_auth.user')),
            ],
            options={
                'verbose_name': 'Vault Note',
                'verbose_name_plural': 'Vault Notes',
                'db_table': 'note_vaultnote',
                'ordering': ['-updated_at'],
            },
        ),
    ]
