# Generated by Django 5.2.15 on 2026-07-12 17:31

import apps.note.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_vaultindex_vaultnote'),
        ('proxima_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this live note', primary_key=True, serialize=False)),
                ('snapshot', models.TextField(help_text='Base64 AES-256-GCM ciphertext of the encoded Yjs document state', validators=[apps.note.validators.validate_live_snapshot])),
                ('snapshot_iv', models.TextField(help_text='Initialization vector for the snapshot (Base64-encoded)', validators=[apps.note.validators.validate_required_iv])),
                ('snapshot_seq', models.BigIntegerField(default=0, help_text='Highest update id folded into the snapshot; 0 when seeded')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this live note was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last snapshot write')),
                ('expires_at', models.DateTimeField(help_text='Timestamp when this live note expires and will be deleted')),
                ('access_count', models.IntegerField(default=0, help_text='Number of times the live page has been opened')),
                ('created_by', models.ForeignKey(blank=True, help_text='Authenticated user that created this live note; empty for anonymous live notes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_notes', to='proxima_auth.user')),
            ],
            options={
                'verbose_name': 'Live Note',
                'verbose_name_plural': 'Live Notes',
                'db_table': 'note_livenote',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveNoteUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField(help_text='Base64 AES-256-GCM ciphertext of one merged Yjs update', validators=[apps.note.validators.validate_live_update_payload])),
                ('iv', models.TextField(help_text='Initialization vector for AES-GCM encryption (Base64-encoded)', validators=[apps.note.validators.validate_required_iv])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this update was appended')),
                ('note', models.ForeignKey(db_index=False, help_text='Live note this update belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='note.livenote')),
            ],
            options={
                'verbose_name': 'Live Note Update',
                'verbose_name_plural': 'Live Note Updates',
                'db_table': 'note_livenoteupdate',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='livenote',
            index=models.Index(fields=['expires_at'], name='note_live_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='livenoteupdate',
            index=models.Index(fields=['note', 'id'], name='note_liveupd_note_id_idx'),
        ),
    ]
