# Generated by Django 5.2.15 on 2026-08-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_livenote_livenoteupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultnote',
            name='trashed_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, help_text='When this note was moved to Trash (null while active)', null=True),
        ),
    ]
