# Generated by Django 5.2.15 on 2026-07-13 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_livenote_livenoteupdate'),
        ('proxima_auth', '0002_userkeypair'),
    ]

    operations = [
        migrations.AddField(
            model_name='livenote',
            name='access_mode',
            field=models.CharField(choices=[('link', 'Anyone with the link'), ('restricted', 'Named collaborators only')], default='link', help_text='Whether the link alone grants access, or a collaborator row is required', max_length=10),
        ),
        migrations.AddField(
            model_name='livenote',
            name='key_epoch',
            field=models.BigIntegerField(default=0, help_text='Document-key generation; incremented on each rekey'),
        ),
        migrations.CreateModel(
            name='LiveNoteCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor')], default='editor', max_length=8)),
                ('wrapped_key', models.TextField(help_text='Base64 AES-GCM ciphertext of the document key, wrapped to this user')),
                ('wrap_iv', models.TextField(help_text='Base64 IV for the wrapped key')),
                ('ephemeral_public_key', models.TextField(help_text="Base64 SPKI of the wrap's ephemeral ECDH public key")),
                ('key_epoch', models.BigIntegerField(default=0, help_text='Document-key generation this wrap decrypts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(help_text='Restricted live note this grant belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='note.livenote')),
                ('user', models.ForeignKey(help_text='The collaborator', on_delete=django.db.models.deletion.CASCADE, related_name='live_collaborations', to='proxima_auth.user')),
            ],
            options={
                'verbose_name': 'Live Note Collaborator',
                'verbose_name_plural': 'Live Note Collaborators',
                'db_table': 'note_livenotecollaborator',
                'indexes': [models.Index(fields=['note', 'user'], name='note_livecollab_note_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('note', 'user'), name='note_livecollab_unique_note_user')],
            },
        ),
    ]
