# Generated by Django 5.2.4 on 2026-06-10 12:19

import apps.passwd.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("proxima_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "encrypted_data",
                    models.TextField(
                        help_text="Client-encrypted JSON blob for the sharing service",
                        validators=[apps.passwd.validators.validate_encrypted_data],
                    ),
                ),
                (
                    "iv",
                    models.BinaryField(
                        help_text="Initialization vector for AES-256-GCM encryption (12 bytes)",
                        max_length=12,
                        validators=[apps.passwd.validators.validate_iv_bytes],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User who owns this encrypted data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_data",
                        to="proxima_auth.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Data",
                "verbose_name_plural": "Service Data",
                "db_table": "passwd_servicedata",
            },
        ),
        migrations.CreateModel(
            name="SharedPassword",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this password share",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "encrypted_data",
                    models.TextField(
                        help_text="Client-side encrypted password data (Base64-encoded ciphertext)",
                        validators=[apps.passwd.validators.validate_encrypted_data],
                    ),
                ),
                (
                    "iv",
                    models.TextField(
                        help_text="Initialization vector for AES-GCM encryption (Base64-encoded)",
                        validators=[apps.passwd.validators.validate_iv],
                    ),
                ),
                (
                    "encrypted_title",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Client-side encrypted title (Base64-encoded ciphertext); empty if none",
                        validators=[
                            apps.passwd.validators.validate_optional_encrypted_title
                        ],
                    ),
                ),
                (
                    "title_iv",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Initialization vector for the encrypted title (Base64-encoded); empty if none",
                        validators=[apps.passwd.validators.validate_optional_iv],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this share was created",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Timestamp when this share expires and will be deleted"
                    ),
                ),
                (
                    "access_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this share has been accessed",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Authenticated user that created this share; empty for anonymous shares",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_passwords",
                        to="proxima_auth.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shared Password",
                "verbose_name_plural": "Shared Passwords",
                "db_table": "passwd_sharedpassword",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["expires_at"], name="passwd_expires_idx"),
                    models.Index(fields=["-created_at"], name="passwd_created_idx"),
                ],
            },
        ),
    ]
