# Generated by Django 5.2.15 on 2026-06-28 16:37

import apps.passwd.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passwd", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicedata",
            name="encrypted_data",
            field=models.TextField(
                help_text="Client-encrypted JSON blob for the sharing service",
                validators=[apps.passwd.validators.validate_vault_data],
            ),
        ),
    ]
